### ISSUE TITLE
cryptic error when recreating a resource that has not been purged

### ISSUE THREAD

**Issue by goneri** [redhat-cip/dci-ansible#11] opened 2018-01-04 14:21 UTC
If a resource has been remove but not purge, the SQL contraint will still take it into account and refuse to create a new resource. The server will return a 409 error and DCI Ansible pop up the following error.

```
TASK [Create OpenStack] **********************************************************************************************
task path: /home/goneri/git_repos/dci-ansible/tests/unit-tests/dci_topic/playbook.yml:9
Using module file /home/goneri/git_repos/dci-ansible/modules/dci_product.py
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: goneri
<127.0.0.1> EXEC /bin/sh -c 'echo ~ && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/goneri/.ansible/tmp/ansible-tmp-1515026454.23-227325190824735 `" && echo ansible-tmp-1515026454.23-227325190824735="` echo /home/goneri/.ansible/tmp/ansible-tmp-1515026454.23-227325190824735 `" ) && sleep 0'
<127.0.0.1> PUT /tmp/tmp5goM0m TO /home/goneri/.ansible/tmp/ansible-tmp-1515026454.23-227325190824735/dci_product.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/goneri/.ansible/tmp/ansible-tmp-1515026454.23-227325190824735/ /home/goneri/.ansible/tmp/ansible-tmp-1515026454.23-227325190824735/dci_product.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/home/goneri/venv/py2/bin/python2 /home/goneri/.ansible/tmp/ansible-tmp-1515026454.23-227325190824735/dci_product.py; rm -rf "/home/goneri/.ansible/tmp/ansible-tmp-1515026454.23-227325190824735/" > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_pxJTJp/ansible_module_dci_product.py", line 164, in <module>
    main()
  File "/tmp/ansible_pxJTJp/ansible_module_dci_product.py", line 158, in main
    result = parse_http_response(http_response, dci_product, context, module)
  File "/tmp/ansible_pxJTJp/ansible_modlib.zip/ansible/module_utils/common.py", line 158, in parse_http_response
IndexError: list index out of range

fatal: [localhost]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_pxJTJp/ansible_module_dci_product.py\", line 164, in <module>\n    main()\n  File \"/tmp/ansible_pxJTJp/ansible_module_dci_product.py\", line 158, in main\n    result = parse_http_response(http_response, dci_product, context, module)\n  File \"/tmp/ansible_pxJTJp/ansible_modlib.zip/ansible/module_utils/common.py\", line 158, in parse_http_response\nIndexError: list index out of range\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE", 
    "rc": 0
}
```

**Comment by Spredzy** [comment] 2018-07-05 16:08
Not reproduced since then. Closing it for now.

**Closed as completed by Spredzy** 2018-07-05 16:08 UTC
Labels: enhancement
